FROM debian
RUN apt-get update
RUN apt-get install -y python3-full
RUN apt-get install -y python3-pip
RUN apt-get install -y libmariadb-dev
RUN apt-get install -y libmariadb-dev-compat
RUN apt-get install -y libmariadb3
RUN pip3 install requests --break-system-packages
RUN pip3 install beautifulsoup4 --break-system-packages
RUN pip3 install pytelegrambotapi --break-system-packages
RUN pip3 install mariadb --break-system-packages
ADD start.py /opt/
ADD bot.py /opt/
ADD parser.py /opt/
ADD settings.ini /opt/
CMD [ "python3", "/opt/bot.py" ]