FROM debian
RUN set -xe \
    && apt-get update \
    && apt-get install -y python3-pip
RUN apt-get install -y libmariadb-dev
RUN apt-get install -y libmariadb-dev-compat
RUN apt-get install -y libmariadb3
RUN pip install requests
RUN pip install beautifulsoup4
RUN pip install pytelegrambotapi
RUN pip install mariadb
ADD start.py /opt/
ADD bot.py /opt/
ADD parser.py /opt/
ADD settings.ini /opt/
CMD [ "python3", "/opt/bot.py" ]